services:

#  fast_api_rest:
#    build: .
#    image: fast_api_rest
#    container_name: fast_api_rest
#    environment:
#      POSTGRES_HOST: "postgres"
#      POSTGRES_PORT: "5432"
#      POSTGRES_DB: "postgres"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#    ports:
#      - "8000:8000"
#    networks:
#      - fast_api_rest_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - fast_api_rest_network

networks:
  fast_api_rest_network:
    driver: bridge
